name: Build Push & Deploy

on:
  workflow_dispatch: {}
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: 'Terraform Setup'
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: 'Terraform Apply'
        id: terraform_plan_apply
        env:
          TF_VAR_security_group_id: ${{ secrets.SECURITY_GROUP_ID }}
        run: |-
          cd infrastructure
          terraform init
          terraform validate
          terraform apply -auto-approve

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # - name: Build and Push Docker Image
      #   env:
      #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #     ECR_REPOSITORY: "hr_pr_review_exercise"
      #     IMAGE_TAG: latest
      #   run: |
      #     docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f app/Dockerfile app
      #     docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      
      - name: 'Get EC2 instance data'
        id: instance_data
        run: |-
          aws ec2 describe-instances --filters 'Name=tag:Name,Values=pr_review_exercise' > instances.json

          running_instance=$(cat instances.json | jq -r 'try (.Reservations[] | select(.Instances[].State.Name=="running")) // ""')

          public_url=$(cat instances.json | jq -r '.Reservations[] | select(.Instances[].State.Name=="running") | .Instances[0] | .PublicDnsName' )
          instance_id=$(cat instances.json | jq -r '.Reservations[] | select(.Instances[].State.Name=="running") | .Instances[0] | .InstanceId' )
          
          now=$(date +%s)
          aws ec2 create-tags --resources "$instance_id" --tags Key=last_update,Value="$now"

          echo "EC2 instance URL: $public_url"
          echo "ECR URL: ${{ steps.login-ecr.outputs.registry }}"

          echo "public_url=$public_url" >> $GITHUB_OUTPUT
          echo "public_key=$public_key" >> $GITHUB_OUTPUT
      - name: Spin up docker
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          INSTANCE_HOSTNAME: ${{ steps.instance_data.outputs.public_url }}
        run: |
          echo "$SSH_KEY" > ssh_key.pem && chmod 600 ssh_key.pem

          ssh -o StrictHostKeyChecking=no -i "ssh_key.pem" ubuntu@${INSTANCE_HOSTNAME} <<- 'EOF'
            sudo apt update &&
            docker --version &&

            aws configure set aws_access_key_id "${{ secrets.AWS_ACCESS_KEY_ID }}" --profile default &&
            aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY }}" --profile default &&
            aws configure set region "us-east-1" --profile default &&
            aws configure set output "text" --profile default &&

            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin "${{ steps.login-ecr.outputs.registry }}" &&

            docker pull ${{ steps.login-ecr.outputs.registry }}/hr_pr_review_exercise:latest
            docker run ${{ steps.login-ecr.outputs.registry }}/hr_pr_review_exercise:latest
          EOF
          
        
